tmp dir moved to /tmp. removed kill command. some cleaning. home moved to ~/.config/mmusic

diff --git a/mmusicd b/mmusicd
--- a/mmusicd
+++ b/mmusicd
@@ -1,122 +1,106 @@
 #!/bin/bash 
 
-home=~/.mmusic
+home="$HOME/.config/mmusic"
 
-playlists=$home/playlists
-upcoming=$home/upcomingmusic
+playlists="$home/playlists"
+upcoming="$home/upcomingmusic"
 
-tmp=$home/tmp
+tmp="/tmp/mmusic-$USER"
+fifo="$tmp/fifo"
+stoploop="$tmp/stoploop"
+playing="$tmp/playing"
+pausedfile="$tmp/paused"
+currentplaylist="$tmp/playlist"
+israndom="$tmp/israndom"
 
-fifo=$tmp/fifo
-stoploop=$tmp/stoploop
-playing=$tmp/playing
-pausedfile=$tmp/paused
-currentplaylist=$tmp/playlist
-israndom=$tmp/israndom
-
-if [[ ! -a "$home" ]]
-then
+if [[ ! -a "$home" ]]; then
     echo "Creating home at \"$home\""
     mkdir "$home"
 fi
 
-if [[ ! -a "$upcoming" ]]
-then
+if [[ ! -a "$upcoming" ]]; then
     touch "$upcoming"
 fi
 
-if [[ ! -a "$tmp" ]]
-then
-    mkdir "$tmp"
-fi
-
-if [[ ! -a "$playlists" ]]
-then
+if [[ ! -a "$playlists" ]]; then
     mkdir "$playlists"
 fi
 
 function usage {
     echo "usage:"
-    echo "   $0 [options]"
-   
-    echo "      list - prints the current playlist files contents"
-    echo "      upcoming - print the upcoming file"
-    echo "      playing - prints the currently playing song or nothing if not playing"
-    
-    echo "      add [playlist|upcoming|next] file-or-folder-to-add - adds file or contents of folder to playlist specified or upcoming"
-    echo "      remove [playlist|upcoming] n - Removes line n from playlist" 
+    echo "   $0 command [options]"
+    echo
+    echo "      help                - shows this."
+    echo
+    echo "      start [playlist]    - starts playing playlist or playlist main if none given."
+    echo
+    echo "      list                - prints the current playlist files contents."
+    echo "      upcoming            - print the upcoming file."
+    echo "      playing             - prints the currently playing song or nothing if not playing."
+    echo
+    echo "      add [playlist|upcoming|next] file-or-folder-to-add"
+    echo "                          - add's the file or all [mp3|flac|m4a|ogg] files inside the folder to playlist. If there is no playlist with that name a new one will be created. If playlist is upcoming then the files are added to upcoming. If next then they are added to the begining of upcoming."
+    echo "      remove [playlist|upcoming] n"
+    echo "                          - Removes line n from playlist." 
+    echo
+    echo "      pause               - pauses playing."
+    echo "      paused              - echos \"yes\" if paused else \"no\" (note: no output if not running)."
+    echo "      stop                - stops the daemon."
+    echo "      skip                - skips current song."
+    echo
+    echo "      clear               - clears the upcoming file."
+    echo "      play file           - plays file."
+    echo
+    echo "      playlists           - lists playlists."
+    echo "      change playlist     - change to playlist (note: will continue playing the current song so you will need to skip if you want to switch to the new playlist imediately)."
+    echo
+}
 
-    echo "      pause - pauses playing"
-    echo "      paused - echos \"yes\" if paused else \"no\" (note: returns no when player stopped)"
-    echo "      stop - kills the daemon"
-    echo "      kill - removes tmp files incase you turned off your computer without stoping this and stop hangs."
-    echo "      skip - skips current song"
-    
-    echo "      clear - clears the upcoming file"
-    echo "      play file - plays file"
-
-    echo "      playlists - lists playlists"
-    echo "      new \"name\" - create a new playlist with name \"name\""
-    echo "      change playlist - change to playlist"
+function checktmp {
+    if [[ ! -a "$tmp" ]]; then
+        exit 1
+    fi
 }
 
 function play {
     old=`cat "$upcoming"`
     song="$1"
-    echo "$song" > $tmp/newup
-    if [[ ! -z "$old" ]]; then
-        echo "$old" >> $tmp/newup
-    fi
-    cat $tmp/newup > "$upcoming"
-    rm $tmp/newup
+    echo "$song" > "$tmp/newup"
+    cat "$upcoming" >> "$tmp/newup"
+    cat "$tmp/newup" > "$upcoming"
+    rm "$tmp/newup"
     echo "quit" > "$fifo"
 
-    if [[ -a "$pausedfile" ]]
-    then
-        rm "$pausedfile"
-    fi
+    [[ -a "$pausedfile" ]] && rm "$pausedfile"
 }
 
 function setplaylist {
-    playlist="$playlists/$1"
+    playlist="$1"
 
-    if [[ ! -a "$playlist" ]]
-    then
-        echo "Could not find playlist with name \"$1\""
-        echo "Note: You can currently not play playlists outside of \"$playlists\""
-        return
+    if [[ ! -a "$playlist" ]]; then
+        playlist="$playlists/$1"
+        if [[ ! -a "$playlist" ]]; then
+            echo "Could not find playlist \"$1\""
+            exit
+        fi
     fi
     
     LINES=`cat "$playlist" | wc -l`
-    if [[ "$LINES" -eq "0" ]]
-    then
+    if [[ "$LINES" -eq "0" ]]; then
         echo "\"$1\" is empty so I will not play it."
-        return;
+        exit
     fi
 
-    echo "$1" > "$currentplaylist"
-
-    if [[ ! -a $playing ]]
-    then
-        echo "Starting"
-        startplaying &
-    else
-        echo "should be playing"
-    fi
+    echo "$playlist" > "$currentplaylist"
 }
 
 function startplaying {
-    if [[ -a "$fifo" ]]
-    then
-        echo "please stop me first!"
-        echo "     thats $0 stop if you forgot"
-        echo "     If that just hangs try killing me with"
-        echo "          $0 kill" 
+   if [[ -a "$fifo" ]]; then
+        exitd
         exit
     fi
     
-    if [[ ! -a $playing ]]
-    then
+    if [[ ! -a $playing ]]; then
         touch $playing
     fi
         
@@ -127,10 +111,8 @@ function startplaying {
     do
         song=`popupcoming`
 
-        if [[ -z "$song" ]]
-        then
-            if [[ -a "$israndom" ]]
-            then
+        if [[ -z "$song" ]]; then
+            if [[ -a "$israndom" ]]; then
                 song=`getrandom`
             else
                 song=`getnext`
@@ -138,21 +120,22 @@ function startplaying {
         fi
 
         echo "$song" > "$playing"
-	mpv --audio-display=no -really-quiet -input-file="$fifo" "$song"
+        mpv --audio-display=no -really-quiet -input-file="$fifo" "$song"
         #mplayer -really-quiet -slave -input file="$fifo" "$song"
 	    
-        if [[ -a "$stoploop" ]]
-        then
+        if [[ -a "$stoploop" ]]; then
             break
         fi
 
         sleep 0.1
     done
    
-    rm $tmp/*
+    rm -r "$tmp"
 }
 
 function popupcoming {
+    checktmp
+
     next=`cat "$upcoming" | head -1`
     echo "$next"
 
@@ -162,7 +145,9 @@ function popupcoming {
 }
 
 function getrandom {
-    playlist=$playlists/`cat "$currentplaylist"`
+    checktmp
+
+    playlist=`cat "$currentplaylist"`
     RAND=`od -d -N2 -An /dev/urandom`
     LINES=`cat "$playlist" | wc -l`
     N=$(( RAND % LINES + 1 ))
@@ -171,25 +156,28 @@ function getrandom {
 }
 
 function getnext {
-    list="$playlists/`cat $currentplaylist`"
+    checktmp
+
     playing_raw="`cat $playing`"
     playing_clean="`echo $playing_raw | sed "s/\[/\\\\\[/g" | sed "s/\]/\\\\\]/g"`"
-    song=`grep -A1 "$playing_clean" $list | tail -n 1`
+    song=`grep -A1 "$playing_clean" "$currentplaylist" | tail -n 1`
     echo "$song"
 }
 
 function skip {
+    checktmp
+
     echo "quit" > "$fifo"
-    if [[ -a "$pausedfile" ]]
-    then
+    if [[ -a "$pausedfile" ]]; then
         rm "$pausedfile"
     fi
 }
 
 function exitd {
+    checktmp
+
     touch "$stoploop"
-    if [[ -a "$fifo" ]]
-    then
+    if [[ -a "$fifo" ]]; then
         echo "quit" > $fifo
     fi
 }
@@ -204,28 +192,25 @@ function add {
     file="$2"
     pos="$1"
 
-    tmp1="$tmp/add_tmp"
+    tmp1="/tmp/add_tmp"
 
     touch "$tmp1"
 
     for f in "${@:3}"
     do
-        if [[ -d "$f" ]]
-        then
+        if [[ -d "$f" ]]; then
             cd "$f"
-            find "$PWD/"* -regextype posix-extended -iregex ".*(mp3|flac|m4a)" >> "$tmp1"
+            find "$PWD/"* -regextype posix-extended -iregex ".*(mp3|flac|m4a|ogg)" >> "$tmp1"
 	   	    
-        elif [[ -a "$f" ]]
-        then
+        elif [[ -a "$f" ]]; then
             echo "$f" >> "$tmp1"
         else
             echo "No such file $f"
         fi
     done
     
-    if [[ "$pos" == "start" ]]
-    then
-        tmp2="$tmp/add_tmp_2"
+    if [[ "$pos" == "start" ]]; then
+        tmp2="/tmp/add_tmp_2"
         cat "$tmp1" > "$tmp2"
         cat "$file" >> "$tmp2"
         cat "$tmp2" > "$file"
@@ -242,97 +227,81 @@ function remove {
     n=$(($2 - 1))
     m=$(($l - $2))
 
-    cat "$1" | head -$n > $tmp/newfile
-    cat "$1" | tail -$m >> $tmp/newfile
-    cat $tmp/newfile > "$1"
-    rm $tmp/newfile
+    cat "$1" | head -$n > /tmp/newfile
+    cat "$1" | tail -$m >> /tmp/newfile
+    cat /tmp/newfile > "$1"
+    rm /tmp/newfile
 }
 
-if [[ "$1" == "play" ]]
-then
+if [[ "$1" == "play" ]]; then
     play "$2"
 
-elif [[ "$1" == "clear" ]]
-then
+elif [[ "$1" == "clear" ]]; then
     rm "$upcoming"
     touch "$upcoming"
 
-elif [[ "$1" == "skip" ]]
-then
+elif [[ "$1" == "skip" ]]; then
     skip
 
-elif [[ "$1" == "stop" ]]
-then
+elif [[ "$1" == "stop" ]]; then
     exitd 
 
-elif [[ "$1" == "kill" ]]
-then
-    rm $tmp/*
-
-elif [[ "$1" == "add" ]]
-then
+elif [[ "$1" == "add" ]]; then
     if [[ "$2" == "upcoming" ]]; then
-	file="$upcoming"
-	pos="end"
+    	file="$upcoming"
+	    pos="end"
     elif [[ "$2" == "next" ]]; then
-	file="$upcoming"
-	pos="start"
+	    file="$upcoming"
+	    pos="start"
     else
-	file="$playlists/$2"
-	if [[ ! -a "$file" ]]; then
-	    touch "$file"
-	fi
-	
-	pos="sort"
+	    file="$playlists/$2"
+	    if [[ ! -a "$file" ]]; then
+	        touch "$file"
+	    fi
+	    pos="sort"
     fi
 	
     add "$pos" "$file" "${@:3}"
     if [[ "$pos" == "sort" ]]; then
-	sortlist "$playlists/$2"
-	add "$sort" "$playlists/main" "${@:3}"
-	sortlist "$playlists/main"
+	    sortlist "$playlists/$2"
+	    add "$sort" "$playlists/main" "${@:3}"
+	    sortlist "$playlists/main"
     fi
     
-elif [[ "$1" == "playing" ]]
-then
-    if [[ -a "$playing" ]]
-    then
+elif [[ "$1" == "playing" ]]; then
+    if [[ -a "$playing" ]]; then
         cat "$playing"
     else
         echo "Not playing"
     fi
 
-elif [[ "$1" == "upcoming" ]]
-then
+elif [[ "$1" == "upcoming" ]]; then
     cat "$upcoming"
 
-elif [[ "$1" == "list" ]]
-then
-    cat $playlists/`cat "$currentplaylist"`
+elif [[ "$1" == "list" ]]; then
+    cat "`cat $currentplaylist`"
 
-elif [[ "$1" == "pause" ]]
-then
+elif [[ "$1" == "pause" ]]; then
+    checktmp
+
     echo "pause" > "$fifo"
-    if [[ -a "$pausedfile" ]]
-    then
+    if [[ -a "$pausedfile" ]]; then
         rm "$pausedfile"
     else
         touch "$pausedfile"
     fi
 
-elif [[ "$1" == "paused" ]]
-then
-    if [[ -a "$pausedfile" ]]
-    then
+elif [[ "$1" == "paused" ]]; then
+    checktmp
+
+    if [[ -a "$pausedfile" ]]; then
         echo "yes"
     else
         echo "no"
     fi
 
-elif [[ "$1" == "remove" ]]
-then
-    if [[ "$2" == "upcoming" ]]
-    then
+elif [[ "$1" == "remove" ]]; then
+    if [[ "$2" == "upcoming" ]]; then
         file="$upcoming"
     else
         file="$playlists/$2"
@@ -340,50 +309,51 @@ then
     
     remove "$file" "$3"
 
-elif [[ "$1" == "random" ]]
-then
-    if [[ -a "$israndom" ]]
-    then
+elif [[ "$1" == "random" ]]; then
+    if [[ -a "$israndom" ]]; then
         rm "$israndom"
     else
         touch "$israndom"
     fi
 
-elif [[ "$1" == "israndom" ]]
-then
-    if [[ -a "$israndom" ]]
-    then
+elif [[ "$1" == "israndom" ]]; then
+    if [[ -a "$israndom" ]]; then
         echo "yes"
     else
         echo "no"
     fi
 
-elif [[ "$1" == "playlists" ]]
-then
+elif [[ "$1" == "playlists" ]]; then
     ls "$playlists"
 
-elif [[ "$1" == "new" ]]
-then
-    touch "$playlists/$2"
+elif [[ "$1" == "change" ]]; then
+    checktmp
 
-elif [[ "$1" == "change" ]]
-then
     setplaylist "$2"
  
-elif [[ "$1" == "currentplaylist" ]]
-then
+elif [[ "$1" == "currentplaylist" ]]; then
+    checktmp
+
     cat "$currentplaylist"
 
-elif [[ "$1" == "--help" ]] || [[  "$1" == "-h" ]]
-then
-    usage
+elif [[ "$1" == "start" ]]; then
+    if [[ ! -a "$tmp" ]]; then
+        mkdir "$tmp";
+    else
+        exitd
+    fi
+    
+    if [[ -z "$2" ]]; then
+        setplaylist "$playlists/main"
+    else
+        setplaylist "$2"
+    fi
 
-elif [[ -n "$1" ]]
-then
-    echo "Playing playlist - $1"
-
-    setplaylist "$1"
-
+    startplaying &
 else
-    $0 main
+    if [[ "$1" != "help" ]]; then
+        echo "Unknown option '$1'"
+    fi
+    usage
 fi
+
